### ISSUE TITLE
Custom description

### ISSUE THREAD

**Issue by thoean** [wparad/Osiris#1]
I am getting a `Aws::CodeDeploy::Errors::DescriptionTooLongException` during a call to `deploy`. The description seems to be constructed as `description: "#{application_name}:#{deployment_group} - #{bucket}_#{File.join(relative_path, "#{version.to_s}.zip")}"`, which can easily sum up to the limit of 100 characters.

One option could be to provide a custom name. Another option a custom pattern (for example the bucket name might not be relevant for some). Or simply trimming the description to 100 characters, which is the current limit.

My current workaround is to use shorter names.

**Comment by wparad** [comment]
What would think of removing the the default description since all of that is provided by the CodeDeploy GUI and then adding an override parameter to the `deploy` [api method](https://github.com/wparad/Osiris/blob/master/lib/osiris/deployment.rb#L26)?

**Comment by thoean** [comment]
This change makes sense. Thanks!
