### ISSUE TITLE
NameError: undefined local variable or method `exception'

### ISSUE THREAD

**Issue by leixiaoyu** [wparad/Osiris#3]
exception is not defined before used in Line 44, resulting NameError if there is an exception thrown during deployment.

https://github.com/wparad/Osiris/blob/master/lib/osiris/deployment.rb#L44

**Comment by wparad** [comment]
Well that's certainly an issue.  I can fix that with a pull request.

**Comment by wparad** [comment]
Does that pull request solve your problem?
